DROP DATABASE SQL_Data;

CREATE DATABASE SQL_Data;

USE SQL_Data;

CREATE TABLE sql_table (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(25) NOT NULL,
  email VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  url VARCHAR(200) NOT NULL
);